export default {
  name: 'tenagaKependidikan',
  title: 'Tenaga Kependidikan',
  type: 'document',
  fields: [
    {
      name: 'posisi',
      title: 'Posisi/Jabatan',
      type: 'string',
      options: {
        list: [
          { title: 'Kepala Sekolah', value: 'kepalaSekolah' },
          { title: 'Komite Sekolah', value: 'komiteSekolah' },
          { title: 'Bendahara Sekolah', value: 'bendaharaSekolah' },
          { title: 'Koordinator TAS', value: 'koordinatorTAS' },
          { title: 'Waka Kurikulum', value: 'wakaKurikulum' },
          { title: 'Waka Kesiswaan', value: 'wakaKesiswaan' },
          { title: 'Waka Sarana & Prasarana', value: 'wakaSarana' },
          { title: 'Koordinator Hubungan Masyarakat', value: 'koordinatorHumas' },
          { title: 'Adm. Persuratan / Arsiparis', value: 'admPersuratanArsiparis' },
          { title: 'Adm. Persuratan / UKS / Humas', value: 'admPersuratanUKSHumas' },
          { title: 'Adm. Kepegawaian & Humas', value: 'admKepegawaianHumas' },
          { title: 'Adm. Kurikulum', value: 'admKurikulum' },
          { title: 'Adm. Kesiswaan', value: 'admKesiswaan' },
          { title: 'Adm. Sarana & Prasarana', value: 'admSarana' },
          { title: 'Pengelola Perpustakaan', value: 'pengelolaPerpustakaan' },
          { title: 'Operator Dapodik', value: 'operatorDapodik' },
          { title: 'Pembina OSIS', value: 'pembinaOSIS' },
          { title: 'Kepala Perpustakaan', value: 'kepalaPerpustakaan' },
          { title: 'Kepala Laboratorium Komputer', value: 'kepalaLabKomputer' },
          { title: 'Kepala Laboratorium IPA', value: 'kepalaLabIPA' },
          { title: 'Koordinator UKS', value: 'koordinatorUKS' },
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'nama',
      title: 'Nama Lengkap',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'foto',
      title: 'Foto Profil',
      type: 'image',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'nip',
      title: 'NIP (Nomor Induk Pegawai)',
      type: 'string',
    },
    {
      name: 'gelar',
      title: 'Gelar Pendidikan',
      type: 'string',
      description: 'Contoh: S.Pd, S.Si, M.A',
    },
    {
      name: 'email',
      title: 'Email',
      type: 'string',
    },
    {
      name: 'nomorTelepon',
      title: 'Nomor Telepon',
      type: 'string',
    },
    {
      name: 'urutan',
      title: 'Urutan Tampil',
      type: 'number',
      description: 'Angka lebih kecil = tampil lebih depan',
    },
  ],
};
